### ISSUE TITLE
Send group images

### ISSUE THREAD

**Issue by spiceybrisket** [YassienW/kik-node-api#1]
Hi,

Just wondering if you're going to update this to make sending group images possible?

Happy to help out in anyway I can

**Comment by YassienW** [comment]
Unfortunately, image sending is too cumbersome to reverse engineer. I don't really have time to reverse engineer other things as well (such as fetching the group list). If someone is willing to provide more info on how the features are implemented, i'd be glad to put in time to add them.

**Comment by YassienW** [comment]
Sending images implemented in 1.1.0
