### ISSUE TITLE
repeated unhandled data notifications

### ISSUE THREAD

**Issue by Charliebaby019** [YassienW/kik-node-api#10]
I noticed i was getting a string of data notifications 
every 30 minutes if no data is recieved 
then if data is receieved its delayed 40 minutes 
and then continues every 30 minutes again.... 

until windows reports that its run out of memory

possibly some message handling functions are missing?

![qqqq](https://user-images.githubusercontent.com/54005644/86518239-b7697380-bdf5-11ea-9384-d352a85c56c1.JPG)

**Comment by YassienW** [comment]
You should be able to find the XML for those unhandled requests in the log file, can you share it here?

**Comment by YassienW** [comment]
Upon checking the logs, i believe those are empty keep alive messages sent periodically. Perhaps in the future they can be ignored. 
If you have specific unhandled messages you can open a new issue.
