### ISSUE TITLE
Get admins and owners, total users, is group public of the group

### ISSUE THREAD

**Issue by Astranaot** [YassienW/kik-node-api#12]
### Below is the following I use currently to retrieve member status of the group and total number of users and if the group is public:
'iqHandler.js':
Within _'if(xmlns === "jabber:iq:roster")':_
![image](https://i.gyazo.com/d4d90f3cca1c1e17058a80bfe614c298.png)

**This will add "users_data", "total" and "ispublic" to the group object**
(You can get who is owner or admin upon 'receivedgroupmsg' by console.log(group.users_data)
(You can get total number of users upon 'receivedgroupmsg' by console.log(group.total)
(You can get if the group is public or private upon 'receivedgroupmsg' by console.log(group.ispublic)

**Comment by YassienW** [comment]
You can get the total number of users by checking the length of the array, i don't see the point in adding an extra property. To check if a group is public or not you can check the code property, private groups have no code.

isOwner and isAdmin properties have been added ebedba31b8de284d042bb6f2a5ff03461cb17829, will be included in the next release

**Comment by YassienW** [comment]
Added isOwner and isAdmin in 3.0.0
