### ISSUE TITLE
Leave Group Function

### ISSUE THREAD

**Issue by Astranaot** [YassienW/kik-node-api#13]
### Below is the following I use currently to leave the group:
_Create File 'g_leaveGroup.js' in Requests Folder_:
![image](https://i.gyazo.com/16cc0986f9abef4a6517f480c725462f.png)

**Call Function:**
`Kik.leaveGroup(group.jid)`

**Notes:**
`Make sure to add the functions to KikClient.js`
![image](https://i.gyazo.com/4538961dc2b076c614fb8dfcaf922942.png)

**Comment by YassienW** [comment]
Implemented in a84631c81e1ca73b1ebe43090559d2484b61ed60

**Comment by YassienW** [comment]
Added in 3.0.0
