### ISSUE TITLE
Profile Change Email Function

### ISSUE THREAD

**Issue by Astranaot** [YassienW/kik-node-api#14]
### Below is the following I use currently to change the profile email:
_Create File 'p_setEmail.js' in Requests Folder_:
![image](https://i.gyazo.com/9b7ad903c7976d9a7815763ba1a3cbbb.png)

**Call Function:**
`Kik.p_setEmail(`email@youuse`, `current_password`);`

**Notes:**
`Make sure to add the functions to KikClient.js`
![image](https://i.gyazo.com/2304fe2d17410898677e9ec11bfaaf96.png)

**Comment by YassienW** [comment]
Implemented in 75563862f71032ffab3d62746ac355fb1c4ff2e6

**Comment by YassienW** [comment]
Added in 3.0.0
