### ISSUE TITLE
Profile Change Password Function

### ISSUE THREAD

**Issue by Astranaot** [YassienW/kik-node-api#15]
### Below is the following I use currently to hange the profile password:
_Create File 'p_setPassword.js' in Requests Folder_:
![image](https://i.gyazo.com/840c6d6a73fb5eedb2b5d479a56ea982.png)

**Call Function:**
`Kik.p_setPassword('new_pass', 'old_pass')`

**Notes:**
`Make sure to add the functions to KikClient.js`
![image](https://i.gyazo.com/ec4a3b8b22acd65548f2bf39930639bb.png)

**Comment by YassienW** [comment]
Implemented in 75563862f71032ffab3d62746ac355fb1c4ff2e6

**Comment by YassienW** [comment]
Added in 3.0.0
