### ISSUE TITLE
Missing "Add a kik user as a friend"

### ISSUE THREAD

**Issue by FireFrog047** [YassienW/kik-node-api#16]
Add a kik user as a friend feature is missing on readme or in API? No mention of this feature on anywhere

**Comment by YassienW** [comment]
It actually is implemented but not in the documentation. I will add it soon.

The following should work
```javascript
Kik.addFriend(jid);
Kik.removeFriend(jid);
```
Let me know if you come across any issues.

**Comment by FireFrog047** [comment]
Sure, Keep up the good work.
