### ISSUE TITLE
Cant access 'friends' from outside of "recievedroster"

### ISSUE THREAD

**Issue by GoodOldPhoenix** [YassienW/kik-node-api#21]
Trying to create a function that checks if the user is already a friend, however I cannot seem to figure it out.

I thought `getRoster(friends)` would return an array like the one within the `"receivedroster"` event `console.log(friends)` from within the `recievedprivatemsg` event.

I have to admit I am very rusty with a limited knowledge of what I am actually doing - this is all a learning experience for me and hope you can help me understand my issue.

**Comment by YassienW** [comment]
I'm not sure if the getRoster function is actually working or not (it's not documented), will take a look at it later.

Regardless though, you can keep track of the friends array you get in the "receivedroster" event

```javascript
let myFriends = [];

Kik.on("receivedroster", (groups, friends) => {
    myFriends = friends;
})

//use myFriends to check anywhere in the code
const friend = myFriends.filter((friend) => friend.jid === lookupJid);
```
Something like that should do, let me know if that works

**Comment by GoodOldPhoenix** [comment]
So I managed to make it 'work' by using 
```
const friend = myFriends.filter((friend) => friend.jid === sender.jid);

if(!friend.includes(sender)) {
```

The only issue now, is the bot seems to need to restart before it registers the person is a friend.

**Comment by YassienW** [comment]
Why so? If you get roster after adding a friend does it not return an updated roster?
