### ISSUE TITLE
Get Info from Username

### ISSUE THREAD

**Issue by Astranaot** [YassienW/kik-node-api#22]
**Get Info from username:**
```
{
    "firstName":"Kik",
    "lastName":"Team",
    "displayPicLastModified":1531418402837,
    "displayPic":"pic_url.jpg"
}
```

**Code (KikClient.js):**
```
Const axios = require('axios');

getInfoFromUsername(username){
    const url = `https://ws2.kik.com/user/${username}`;
    axios(url).then(response => {
        const htmlToObj = response.data;
        return htmlToObj;
    }).catch();
    return null;
}
```

**Comment by YassienW** [comment]
I believe the current getUserInfo function is capable of returning the same data via username?

**Comment by bluemods** [comment]
This function is rate limited on Kik's website, and will start to say "Not found".

Also, the request is slow compared to requesting it via XMPP, and does not provide the JID or entity data.

Stick to using `getUserInfo()`
