### ISSUE TITLE
Make message seen  by the bot 

### ISSUE THREAD

**Issue by elmissouri16** [YassienW/kik-node-api#35]
is there any function to mark the message been received and  seen on private events

**Comment by BaconPeeks** [comment]
If you refer to the readme of the GitHub it lists all statements, Eventemitters etc. For the bots and here;s what you're looking for:

Kik.sendMessage(jid, msg, (delivered, read) => {
    if(delivered){
        console.log("Delivered")
    }else if(read){
        console.log("Read")
    }
})


Unless you're after sending a receipt to the sender

**Comment by elmissouri16** [comment]
@BaconPeeks  thanks for the reply and yes I'm referring to sending a receipt to the sender

**Comment by BaconPeeks** [comment]
> @BaconPeeks thanks for the reply and yes I'm referring to sending a receipt to the sender

You would have to modify the API to send the receipts back.

**Comment by elmissouri16** [comment]
> > @BaconPeeks thanks for the reply and yes I'm referring to sending a receipt to the sender
> 
> You would have to modify the API to send the receipts back.

ok thank you
