### ISSUE TITLE
Profile/Group Change Name

### ISSUE THREAD

**Issue by DudillyDev** [YassienW/kik-node-api#4]
/* Part 1: */
Location: kik-node-api\src\kikClient.js = add:
`const g_changeName = require("./requests/g_changeName");`
`const p_changeName = require("./requests/p_changeName");`

Add anywhere in KikClient within KikClient class:
Profile Change Name:
<img src=https://i.gyazo.com/dab7f26285ee8a7ea1e2685cba1f67d5.png></img>

Change Group Name:
<img src=https://i.gyazo.com/a5c4cdfbeae33be409f2f39780cb1dd5.png></img>

/* Part 2: */
Location: kik-node-api\src\requests = create file:
p_changeName.js
g_changeName.js

p_changeName Code:
<img src=https://i.gyazo.com/a8d81dd730602c12229f5b11ae87d07a.png></img>

g_changeName Code:
<img src=https://i.gyazo.com/3a10f151ef6f145fd03014c0cee82db6.png></img>

Call function:
`Kik.g_changeName(group.jid, "Group Name");`
`Kik.p_changeName("Firstname, "Lastname"`

**Comment by YassienW** [comment]
Looks good! I'll test it out and add it if all goes well. Thanks.

**Comment by YassienW** [comment]
Implemented in 1.1.0
