### ISSUE TITLE
packet size limitation

### ISSUE THREAD

**Issue by Charliebaby019** [YassienW/kik-node-api#8]
(excuse me if my github etiquette is lacking, total newb here as you know)
but....
kikconnection.js
if(data.length >= 16384)

regarding this data size amount, im coming across two issues

1 (seems to be purely a server side issue)
but "hidden" groups are shown listed in this first packet i recieve, groups that don't show in my apps listings. UNLESS there are other users than myself listed in them (usually its just me) then i must  add those users to a functioning group, then start a pm with them. only then will the group we share in common appear in the app, and then i can actually leave the group.
....... which besides just being over all interesting..... is causing me to just get a listing of glitched groups within the first received packet...... and then the roster/group listing of the API, just terminats because its hit the packet size limit.... causing me to be unable to proceed to the actual functioning groups that would be displayed by the next full packet

2. how can i code this function to continue to produce more packet results?
(because im ignorant as discussed and highlighted in shame and dispair ....ealier )

**Comment by YassienW** [comment]
The current function only supports a packet that is split into 2 parts, anything more will indeed break it. I'm a bit confused about the first issue, will fixing the packet division limit fix the first issue?

**Comment by Charliebaby019** [comment]
i'm not sure. i think there is something wrong with that particular account the more ive looked at it.

I had just now returned to actually deleted this entry honestly.

 seems to be a chunk of time in which any group i tried to leave, retained me as a user but just wouldnt show it in the app. but before and after this small sliver of time, there are no lingering groups.

must also consider the account has been in an abtesting mode (ever since i ran linksys mod long ago) ... allows me STILL even without the mod, view and edit group descriptions in group info pages. while all other users cannot.

i do believe its all caused my linksys making perminant changes to the account during that time somehow

**Comment by Charliebaby019** [comment]
oh..... and i can't join groups.
i could, say, two months ago, and i havent checked since then until today, and today it cannot join groups. but 

other accounts using the nodejs API today, have no problem joining new groups.

i think im just going to kick out that account and tell it to go get a job. and never come back

**Comment by YassienW** [comment]
The packet limitation is still a problem though? If that is the case i'll get it fixed

**Comment by Charliebaby019** [comment]
i suppose that could be very useful

**Comment by Charliebaby019** [comment]
imgManager!?!? OOOOOOOOOO!! exciting!!

**Comment by YassienW** [comment]
I'm gonna close this since we're not certain that this is actually causing any problems, if it is let me know and i'll fix it.
